/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import Network.Client.GameClient
import edu.austral.dissis.chess.gui.CachedImageResolver
import edu.austral.dissis.chess.gui.DefaultImageResolver
import edu.austral.dissis.chess.gui.GameView
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage
import edu.austral.ingsis.clientserver.netty.client.NettyClientBuilder


fun main() {
    launch(ChessGameClient2::class.java)
}

class ChessGameClient2 : Application() {
    private val imageResolver = CachedImageResolver(DefaultImageResolver())
    private val root = GameView(imageResolver)
    private val builder = NettyClientBuilder.createDefault()
    private val client = GameClient(root, builder)

    override fun start(primaryStage: Stage) {
        primaryStage.title = "Network/Client"

        primaryStage.scene = Scene(root)

        primaryStage.show()
    }
}